#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <stdbool.h>

typedef enum {
  TYPE_STRING,
  TYPE_INT,
  TYPE_BOOL
} ValueType;


typedef struct {
    const char* name;
    ValueType type;
    const char* valid_values[5]; // Usado apenas para tipos booleanos ou listas fixas
} ConfigOption;

static const ConfigOption config_options[] = {
    {"rc_debug", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rc_info", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rc_startmsgs", TYPE_BOOL, {"YES", "NO", NULL}},
    {"always_force_depends", TYPE_BOOL, {"YES", "NO", NULL}},
    {"apm_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"apmd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ddb_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"devd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"devmatch_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kldxref_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kldxref_clobber", TYPE_BOOL, {"YES", "NO", NULL}},
    {"powerd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rcshutdown_timeout", TYPE_INT, {NULL}},
    {"early_late_divider", TYPE_STRING, {NULL}},
    {"ddb_config", TYPE_STRING, {NULL}},
    {"devmatch_blocklist", TYPE_STRING, {NULL}},
    {"kldxref_module_path", TYPE_STRING, {NULL}},
    {"apmd_flags", TYPE_STRING, {NULL}},
    {"devd_flags", TYPE_STRING, {NULL}},
    {"powerd_flags", TYPE_STRING, {NULL}},
    {"tmpmfs", TYPE_BOOL, {"YES", "NO", "AUTO", NULL}},
    {"tmpsize", TYPE_STRING, {NULL}},
    {"tmpmfs_flags", TYPE_STRING, {NULL}},
    {"varmfs", TYPE_BOOL, {"YES", "NO", "AUTO", NULL}},
    {"varsize", TYPE_STRING, {NULL}},
    {"varmfs_flags", TYPE_STRING, {NULL}},
    {"mfs_type", TYPE_STRING, {NULL}},
    {"populate_var", TYPE_BOOL, {"YES", "NO", "AUTO", NULL}},
    {"cleanvar_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"var_run_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"var_run_autosave", TYPE_BOOL, {"YES", "NO", NULL}},
    {"var_run_mtree", TYPE_STRING, {NULL}},
    {"local_startup", TYPE_STRING, {NULL}},
    {"script_name_sep", TYPE_STRING, {NULL}},
    {"rc_conf_files", TYPE_STRING, {NULL}},
    {"zfs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"zfskeys_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"zfs_bootonce_activate", TYPE_BOOL, {"YES", "NO", NULL}},
    {"zpool_reguid", TYPE_STRING, {NULL}},
        {"gptboot_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"gbde_autoattach_all", TYPE_BOOL, {"YES", "NO", NULL}},
    {"gbde_devices", TYPE_STRING, {NULL}},
    {"gbde_attach_attempts", TYPE_INT, {NULL}},
    {"gbde_lockdir", TYPE_STRING, {NULL}},
    {"geli_devices", TYPE_STRING, {NULL}},
    {"geli_groups", TYPE_STRING, {NULL}},
    {"geli_tries", TYPE_INT, {NULL}},
    {"geli_default_flags", TYPE_STRING, {NULL}},
    {"geli_autodetach", TYPE_BOOL, {"YES", "NO", NULL}},
    {"root_rw_mount", TYPE_BOOL, {"YES", "NO", NULL}},
    {"root_hold_delay", TYPE_INT, {NULL}},
    {"fsck_flags", TYPE_STRING, {NULL}},
    {"fsck_y_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"fsck_y_flags", TYPE_STRING, {NULL}},
    {"background_fsck", TYPE_BOOL, {"YES", "NO", NULL}},
    {"background_fsck_delay", TYPE_INT, {NULL}},
    {"growfs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"growfs_swap_size", TYPE_STRING, {NULL}},
    {"netfs_types", TYPE_STRING, {NULL}},
    {"extra_netfs_types", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hostname", TYPE_STRING, {NULL}},
    {"hostid_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hostid_file", TYPE_STRING, {NULL}},
    {"hostid_uuidgen_flags", TYPE_STRING, {NULL}},
    {"machine_id_file", TYPE_STRING, {NULL}},
    {"nisdomainname", TYPE_BOOL, {"YES", "NO", NULL}},
    {"dhclient_program", TYPE_STRING, {NULL}},
    {"dhclient_flags", TYPE_STRING, {NULL}},
    {"background_dhclient", TYPE_BOOL, {"YES", "NO", NULL}},
    {"synchronous_dhclient", TYPE_BOOL, {"YES", "NO", NULL}},
    {"defaultroute_delay", TYPE_INT, {NULL}},
    {"defaultroute_carrier_delay", TYPE_INT, {NULL}},
    {"netif_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"netif_ipexpand_max", TYPE_INT, {NULL}},
    {"wpa_supplicant_program", TYPE_STRING, {NULL}},
    {"wpa_supplicant_flags", TYPE_STRING, {NULL}},
    {"wpa_supplicant_conf_file", TYPE_STRING, {NULL}},
    {"firewall_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_script", TYPE_STRING, {NULL}},
    {"firewall_type", TYPE_STRING, {NULL}},
    {"firewall_quiet", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_logging", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_logif", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_flags", TYPE_STRING, {NULL}},
    {"firewall_coscripts", TYPE_STRING, {NULL}},
    {"firewall_client_net", TYPE_STRING, {NULL}},
    {"firewall_simple_iif", TYPE_STRING, {NULL}},
    {"firewall_simple_inet", TYPE_STRING, {NULL}},
    {"firewall_simple_oif", TYPE_STRING, {NULL}},
    {"firewall_simple_onet", TYPE_STRING, {NULL}},
    {"firewall_myservices", TYPE_STRING, {NULL}},
    {"firewall_allowservices", TYPE_STRING, {NULL}},
    {"firewall_trusted", TYPE_STRING, {NULL}},
    {"firewall_logdeny", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_nologports", TYPE_STRING, {NULL}},
    {"firewall_nat_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_nat_interface", TYPE_STRING, {NULL}},
    {"firewall_nat_flags", TYPE_STRING, {NULL}},
    {"firewall_nat64_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_nptv6_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_pmod_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"dummynet_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipfw_netflow_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ip_portrange_first", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ip_portrange_last", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ike_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ike_program", TYPE_STRING, {NULL}},
    {"ike_flags", TYPE_STRING, {NULL}},
    {"ipsec_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipsec_file", TYPE_STRING, {NULL}},
    {"natd_program", TYPE_STRING, {NULL}},
    {"natd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"natd_interface", TYPE_STRING, {NULL}},
    {"natd_flags", TYPE_STRING, {NULL}},
    {"ipfilter_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipfilter_program", TYPE_STRING, {NULL}},
    {"ipfilter_rules", TYPE_STRING, {NULL}},
    {"ipfilter_flags", TYPE_STRING, {NULL}},
    {"ippool_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ippool_program", TYPE_STRING, {NULL}},
    {"ippool_rules", TYPE_STRING, {NULL}},
    {"ippool_flags", TYPE_STRING, {NULL}},
    {"ipnat_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipnat_program", TYPE_STRING, {NULL}},
    {"ipnat_rules", TYPE_STRING, {NULL}},
    {"ipnat_flags", TYPE_STRING, {NULL}},
    {"ipmon_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipmon_program", TYPE_STRING, {NULL}},
    {"ipmon_flags", TYPE_STRING, {NULL}},
    {"ipfs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipfs_program", TYPE_STRING, {NULL}},
    {"ipfs_flags", TYPE_STRING, {NULL}},
    {"pf_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pf_rules", TYPE_STRING, {NULL}},
    {"pf_program", TYPE_STRING, {NULL}},
    {"pf_flags", TYPE_STRING, {NULL}},
    {"pf_fallback_rules_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pf_fallback_rules", TYPE_STRING, {NULL}},
    {"pf_fallback_rules_file", TYPE_STRING, {NULL}},
    {"pflog_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pflog_logfile", TYPE_STRING, {NULL}},
    {"pflog_program", TYPE_STRING, {NULL}},
    {"pflog_flags", TYPE_STRING, {NULL}},
    {"ftpproxy_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ftpproxy_flags", TYPE_STRING, {NULL}},
    {"pfsync_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pfsync_syncdev", TYPE_STRING, {NULL}},
    {"pfsync_syncpeer", TYPE_STRING, {NULL}},
    {"pfsync_ifconfig", TYPE_STRING, {NULL}}
};

#endif
