#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <stdlib.h>
#include <stdbool.h>

typedef enum {
  TYPE_STRING,
  TYPE_INT,
  TYPE_BOOL
} ValueType;


typedef struct {
    const char* name;
    ValueType type;
    const char* valid_values[5];
} ConfigOption;

static const ConfigOption config_options[] = {
    {"rc_debug", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rc_info", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rc_startmsgs", TYPE_BOOL, {"YES", "NO", NULL}},
    {"always_force_depends", TYPE_BOOL, {"YES", "NO", NULL}},
    {"apm_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"apmd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ddb_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"devd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"devmatch_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kldxref_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kldxref_clobber", TYPE_BOOL, {"YES", "NO", NULL}},
    {"powerd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rcshutdown_timeout", TYPE_INT, {NULL}},
    {"early_late_divider", TYPE_STRING, {NULL}},
    {"ddb_config", TYPE_STRING, {NULL}},
    {"devmatch_blocklist", TYPE_STRING, {NULL}},
    {"kldxref_module_path", TYPE_STRING, {NULL}},
    {"apmd_flags", TYPE_STRING, {NULL}},
    {"devd_flags", TYPE_STRING, {NULL}},
    {"powerd_flags", TYPE_STRING, {NULL}},
    {"tmpmfs", TYPE_BOOL, {"YES", "NO", "AUTO", NULL}},
    {"tmpsize", TYPE_STRING, {NULL}},
    {"tmpmfs_flags", TYPE_STRING, {NULL}},
    {"varmfs", TYPE_BOOL, {"YES", "NO", "AUTO", NULL}},
    {"varsize", TYPE_STRING, {NULL}},
    {"varmfs_flags", TYPE_STRING, {NULL}},
    {"mfs_type", TYPE_STRING, {NULL}},
    {"populate_var", TYPE_BOOL, {"YES", "NO", "AUTO", NULL}},
    {"cleanvar_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"var_run_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"var_run_autosave", TYPE_BOOL, {"YES", "NO", NULL}},
    {"var_run_mtree", TYPE_STRING, {NULL}},
    {"local_startup", TYPE_STRING, {NULL}},
    {"script_name_sep", TYPE_STRING, {NULL}},
    {"rc_conf_files", TYPE_STRING, {NULL}},
    {"zfs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"zfskeys_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"zfs_bootonce_activate", TYPE_BOOL, {"YES", "NO", NULL}},
    {"zpool_reguid", TYPE_STRING, {NULL}},
    {"gptboot_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"gbde_autoattach_all", TYPE_BOOL, {"YES", "NO", NULL}},
    {"gbde_devices", TYPE_STRING, {NULL}},
    {"gbde_attach_attempts", TYPE_INT, {NULL}},
    {"gbde_lockdir", TYPE_STRING, {NULL}},
    {"geli_devices", TYPE_STRING, {NULL}},
    {"geli_groups", TYPE_STRING, {NULL}},
    {"geli_tries", TYPE_INT, {NULL}},
    {"geli_default_flags", TYPE_STRING, {NULL}},
    {"geli_autodetach", TYPE_BOOL, {"YES", "NO", NULL}},
    {"root_rw_mount", TYPE_BOOL, {"YES", "NO", NULL}},
    {"root_hold_delay", TYPE_INT, {NULL}},
    {"fsck_flags", TYPE_STRING, {NULL}},
    {"fsck_y_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"fsck_y_flags", TYPE_STRING, {NULL}},
    {"background_fsck", TYPE_BOOL, {"YES", "NO", NULL}},
    {"background_fsck_delay", TYPE_INT, {NULL}},
    {"growfs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"growfs_swap_size", TYPE_STRING, {NULL}},
    {"netfs_types", TYPE_STRING, {NULL}},
    {"extra_netfs_types", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hostname", TYPE_STRING, {NULL}},
    {"hostid_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hostid_file", TYPE_STRING, {NULL}},
    {"hostid_uuidgen_flags", TYPE_STRING, {NULL}},
    {"machine_id_file", TYPE_STRING, {NULL}},
    {"nisdomainname", TYPE_BOOL, {"YES", "NO", NULL}},
    {"dhclient_program", TYPE_STRING, {NULL}},
    {"dhclient_flags", TYPE_STRING, {NULL}},
    {"background_dhclient", TYPE_BOOL, {"YES", "NO", NULL}},
    {"synchronous_dhclient", TYPE_BOOL, {"YES", "NO", NULL}},
    {"defaultroute_delay", TYPE_INT, {NULL}},
    {"defaultroute_carrier_delay", TYPE_INT, {NULL}},
    {"netif_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"netif_ipexpand_max", TYPE_INT, {NULL}},
    {"wpa_supplicant_program", TYPE_STRING, {NULL}},
    {"wpa_supplicant_flags", TYPE_STRING, {NULL}},
    {"wpa_supplicant_conf_file", TYPE_STRING, {NULL}},
    {"firewall_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_script", TYPE_STRING, {NULL}},
    {"firewall_type", TYPE_STRING, {NULL}},
    {"firewall_quiet", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_logging", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_logif", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_flags", TYPE_STRING, {NULL}},
    {"firewall_coscripts", TYPE_STRING, {NULL}},
    {"firewall_client_net", TYPE_STRING, {NULL}},
    {"firewall_simple_iif", TYPE_STRING, {NULL}},
    {"firewall_simple_inet", TYPE_STRING, {NULL}},
    {"firewall_simple_oif", TYPE_STRING, {NULL}},
    {"firewall_simple_onet", TYPE_STRING, {NULL}},
    {"firewall_myservices", TYPE_STRING, {NULL}},
    {"firewall_allowservices", TYPE_STRING, {NULL}},
    {"firewall_trusted", TYPE_STRING, {NULL}},
    {"firewall_logdeny", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_nologports", TYPE_STRING, {NULL}},
    {"firewall_nat_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_nat_interface", TYPE_STRING, {NULL}},
    {"firewall_nat_flags", TYPE_STRING, {NULL}},
    {"firewall_nat64_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_nptv6_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firewall_pmod_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"dummynet_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipfw_netflow_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ip_portrange_first", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ip_portrange_last", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ike_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ike_program", TYPE_STRING, {NULL}},
    {"ike_flags", TYPE_STRING, {NULL}},
    {"ipsec_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipsec_file", TYPE_STRING, {NULL}},
    {"natd_program", TYPE_STRING, {NULL}},
    {"natd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"natd_interface", TYPE_STRING, {NULL}},
    {"natd_flags", TYPE_STRING, {NULL}},
    {"ipfilter_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipfilter_program", TYPE_STRING, {NULL}},
    {"ipfilter_rules", TYPE_STRING, {NULL}},
    {"ipfilter_flags", TYPE_STRING, {NULL}},
    {"ippool_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ippool_program", TYPE_STRING, {NULL}},
    {"ippool_rules", TYPE_STRING, {NULL}},
    {"ippool_flags", TYPE_STRING, {NULL}},
    {"ipnat_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipnat_program", TYPE_STRING, {NULL}},
    {"ipnat_rules", TYPE_STRING, {NULL}},
    {"ipnat_flags", TYPE_STRING, {NULL}},
    {"ipmon_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipmon_program", TYPE_STRING, {NULL}},
    {"ipmon_flags", TYPE_STRING, {NULL}},
    {"ipfs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipfs_program", TYPE_STRING, {NULL}},
    {"ipfs_flags", TYPE_STRING, {NULL}},
    {"pf_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pf_rules", TYPE_STRING, {NULL}},
    {"pf_program", TYPE_STRING, {NULL}},
    {"pf_flags", TYPE_STRING, {NULL}},
    {"pf_fallback_rules_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pf_fallback_rules", TYPE_STRING, {NULL}},
    {"pf_fallback_rules_file", TYPE_STRING, {NULL}},
    {"pflog_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pflog_logfile", TYPE_STRING, {NULL}},
    {"pflog_program", TYPE_STRING, {NULL}},
    {"pflog_flags", TYPE_STRING, {NULL}},
    {"ftpproxy_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ftpproxy_flags", TYPE_STRING, {NULL}},
    {"pfsync_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pfsync_syncdev", TYPE_STRING, {NULL}},
    {"pfsync_syncpeer", TYPE_STRING, {NULL}},
    {"pfsync_ifconfig", TYPE_STRING, {NULL}},
    {"tcp_extensions", TYPE_BOOL, {"YES", "NO", NULL}},
    {"log_in_vain", TYPE_INT, {NULL}},
    {"tcp_keepalive", TYPE_BOOL, {"YES", "NO", NULL}},
    {"tcp_drop_synfin", TYPE_BOOL, {"YES", "NO", NULL}},
    {"icmp_drop_redirect", TYPE_STRING, {NULL}},
    {"icmp_log_redirect", TYPE_BOOL, {"YES", "NO", NULL}},
    {"network_interfaces", TYPE_STRING, {NULL}},
    {"cloned_interfaces", TYPE_STRING, {NULL}},
    {"sppp_interfaces", TYPE_STRING, {NULL}},
    {"ppp_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ppp_program", TYPE_STRING, {NULL}},
    {"ppp_mode", TYPE_STRING, {NULL}},
    {"ppp_nat", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ppp_profile", TYPE_STRING, {NULL}},
    {"ppp_user", TYPE_STRING, {NULL}},
    {"hostapd_program", TYPE_STRING, {NULL}},
    {"hostapd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"syslogd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"syslogd_program", TYPE_STRING, {NULL}},
    {"syslogd_flags", TYPE_STRING, {NULL}},
    {"syslogd_oomprotect", TYPE_BOOL, {"YES", "NO", NULL}},
    {"altlog_proglist", TYPE_STRING, {NULL}},
    {"inetd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"inetd_program", TYPE_STRING, {NULL}},
    {"inetd_flags", TYPE_STRING, {NULL}},
    {"iscsid_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"iscsictl_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"iscsictl_flags", TYPE_STRING, {NULL}},
    {"hastd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hastd_program", TYPE_STRING, {NULL}},
    {"hastd_flags", TYPE_STRING, {NULL}},
    {"ctld_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"local_unbound_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"local_unbound_tls", TYPE_BOOL, {"YES", "NO", NULL}},
    {"blacklistd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"blacklistd_flags", TYPE_STRING, {NULL}},
    {"resolv_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kdc_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kdc_program", TYPE_STRING, {NULL}},
    {"kdc_flags", TYPE_STRING, {NULL}},
    {"kadmind_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kadmind_program", TYPE_STRING, {NULL}},
    {"kpasswdd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kpasswdd_program", TYPE_STRING, {NULL}},
    {"kfd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kfd_program", TYPE_STRING, {NULL}},
    {"kfd_flags", TYPE_STRING, {NULL}},
    {"ipropd_master_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipropd_master_program", TYPE_STRING, {NULL}},
    {"ipropd_master_flags", TYPE_STRING, {NULL}},
    {"ipropd_master_keytab", TYPE_STRING, {NULL}},
    {"ipropd_master_slaves", TYPE_STRING, {NULL}},
    {"ipropd_slave_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipropd_slave_program", TYPE_STRING, {NULL}},
    {"ipropd_slave_flags", TYPE_STRING, {NULL}},
    {"ipropd_slave_keytab", TYPE_STRING, {NULL}},
    {"ipropd_slave_master", TYPE_STRING, {NULL}},
    {"gssd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"gssd_program", TYPE_STRING, {NULL}},
    {"gssd_flags", TYPE_STRING, {NULL}},
    {"rwhod_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rwhod_flags", TYPE_STRING, {NULL}},
    {"rarpd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rarpd_flags", TYPE_STRING, {NULL}},
    {"bootparamd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"bootparamd_flags", TYPE_STRING, {NULL}},
    {"pppoed_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"pppoed_provider", TYPE_STRING, {NULL}},
    {"pppoed_flags", TYPE_STRING, {NULL}},
    {"pppoed_interface", TYPE_STRING, {NULL}},
    {"sshd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"sshd_program", TYPE_STRING, {NULL}},
    {"sshd_flags", TYPE_STRING, {NULL}},
    {"ftpd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ftpd_program", TYPE_STRING, {NULL}},
    {"ftpd_flags", TYPE_STRING, {NULL}},
    {"autofs_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"automount_flags", TYPE_STRING, {NULL}},
    {"automountd_flags", TYPE_STRING, {NULL}},
    {"autounmountd_flags", TYPE_STRING, {NULL}},
    {"nfs_client_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfs_access_cache", TYPE_STRING, {NULL}},
    {"nfs_server_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfs_server_flags", TYPE_STRING, {NULL}},
    {"nfs_server_managegids", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfs_server_maxio", TYPE_STRING, {NULL}},
    {"mountd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"mountd_flags", TYPE_STRING, {NULL}},
    {"weak_mountd_authentication", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfs_reserved_port_only", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfs_bufpackets", TYPE_STRING, {NULL}},
    {"rpc_lockd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rpc_lockd_flags", TYPE_STRING, {NULL}},
    {"rpc_statd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rpc_statd_flags", TYPE_STRING, {NULL}},
    {"rpcbind_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rpcbind_program", TYPE_STRING, {NULL}},
    {"rpcbind_flags", TYPE_STRING, {NULL}},
    {"rpc_ypupdated_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"keyserv_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"keyserv_flags", TYPE_STRING, {NULL}},
    {"nfsv4_server_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfsv4_server_only", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfscbd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfscbd_flags", TYPE_STRING, {NULL}},
    {"nfsuserd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nfsuserd_flags", TYPE_STRING, {NULL}},
    {"tlsclntd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"tlsclntd_flags", TYPE_STRING, {NULL}},
    {"tlsservd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"tlsservd_flags", TYPE_STRING, {NULL}},
    {"ntpdate_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ntpdate_program", TYPE_STRING, {NULL}},
    {"ntpdate_flags", TYPE_STRING, {NULL}},
    {"ntpdate_config", TYPE_STRING, {NULL}},
    {"ntpdate_hosts", TYPE_STRING, {NULL}},
    {"ntpd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ntpd_program", TYPE_STRING, {NULL}},
    {"ntpd_config", TYPE_STRING, {NULL}},
    {"ntpd_sync_on_start", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ntpd_flags", TYPE_STRING, {NULL}},
    {"ntp_src_leapfile", TYPE_STRING, {NULL}},
    {"ntp_db_leapfile", TYPE_STRING, {NULL}},
    {"ntp_leapfile_sources", TYPE_STRING, {NULL}},
    {"ntp_leapfile_fetch_opts", TYPE_STRING, {NULL}},
    {"ntp_leapfile_expiry_days", TYPE_STRING, {NULL}},
    {"ntp_leapfile_fetch_verbose", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_client_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_client_flags", TYPE_STRING, {NULL}},
    {"nis_ypset_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_ypset_flags", TYPE_STRING, {NULL}},
    {"nis_server_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_server_flags", TYPE_STRING, {NULL}},
    {"nis_ypxfrd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_ypxfrd_flags", TYPE_STRING, {NULL}},
    {"nis_yppasswdd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_yppasswdd_flags", TYPE_STRING, {NULL}},
    {"nis_ypldap_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"nis_ypldap_flags", TYPE_STRING, {NULL}},
    {"bsnmpd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"bsnmpd_flags", TYPE_STRING, {NULL}},
    {"defaultrouter", TYPE_BOOL, {"YES", "NO", NULL}},
    {"static_arp_pairs", TYPE_STRING, {NULL}},
    {"static_ndp_pairs", TYPE_STRING, {NULL}},
    {"static_routes", TYPE_STRING, {NULL}},
    {"gateway_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"routed_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"routed_program", TYPE_STRING, {NULL}},
    {"routed_flags", TYPE_STRING, {NULL}},
    {"arpproxy_all", TYPE_BOOL, {"YES", "NO", NULL}},
    {"forward_sourceroute", TYPE_BOOL, {"YES", "NO", NULL}},
    {"accept_sourceroute", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hcsecd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"hcsecd_config", TYPE_STRING, {NULL}},
    {"sdpd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"sdpd_control", TYPE_STRING, {NULL}},
    {"sdpd_groupname", TYPE_STRING, {NULL}},
    {"sdpd_username", TYPE_STRING, {NULL}},
    {"bthidd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"bthidd_config", TYPE_STRING, {NULL}},
    {"bthidd_hids", TYPE_STRING, {NULL}},
    {"bthidd_evdev_support", TYPE_STRING, {"AUTO", NULL}},
    {"rfcomm_pppd_server_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rfcomm_pppd_server_profile", TYPE_STRING, {NULL}},
    {"rfcomm_pppd_server_one_channel", TYPE_STRING, {NULL}},
    {"rfcomm_pppd_server_two_channel", TYPE_STRING, {NULL}},
    {"ubthidhci_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"netwait_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    // {"netwait_ip", TYPE_STRING, {NULL}},  // Uncomment to enable and set netwait_ip
    {"netwait_timeout", TYPE_INT, {NULL}},
    // {"netwait_if", TYPE_STRING, {NULL}},  // Uncomment to enable and set netwait_if
    {"netwait_if_timeout", TYPE_INT, {NULL}},
    {"icmp_bmcastecho", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipv6_network_interfaces", TYPE_STRING, {"auto", "none", NULL}},
    {"ipv6_activate_all_interfaces", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipv6_defaultrouter", TYPE_BOOL, {"YES", "NO", NULL}},
    // {"ipv6_defaultrouter", TYPE_STRING, {NULL}},  // Uncomment to set ipv6_defaultrouter
    // {"ipv6_defaultrouter_fibN", TYPE_STRING, {NULL}},  // Uncomment to set ipv6_defaultrouter_fibN
    {"ipv6_static_routes", TYPE_STRING, {NULL}},
    // {"ipv6_static_routes", TYPE_STRING, {NULL}},  // Uncomment to set ipv6_static_routes
    // {"ipv6_route_xxx", TYPE_STRING, {NULL}},  // Uncomment to set ipv6_route_xxx
    {"ipv6_gateway_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipv6_cpe_wanif", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipv6_privacy", TYPE_BOOL, {"YES", "NO", NULL}},
    {"route6d_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"route6d_program", TYPE_STRING, {NULL}},
    {"route6d_flags", TYPE_STRING, {NULL}},
    // {"ipv6_network_interfaces", TYPE_STRING, {NULL}},  // Uncomment to set ipv6_network_interfaces
    // {"ipv6_prefix_emX", TYPE_STRING, {NULL}},  // Uncomment to set ipv6_prefix_emX
    {"ipv6_default_interface", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rtsol_flags", TYPE_STRING, {NULL}},
    {"rtsold_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rtsold_flags", TYPE_STRING, {NULL}},
    {"rtadvd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rtadvd_interfaces", TYPE_STRING, {NULL}},
    {"stf_interface_ipv4addr", TYPE_STRING, {NULL}},
    {"stf_interface_ipv4plen", TYPE_INT, {NULL}},
    {"stf_interface_ipv6_ifid", TYPE_STRING, {NULL}},
    {"stf_interface_ipv6_slaid", TYPE_STRING, {NULL}},
    {"ipv6_ipv4mapping", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ipv6_ipfilter_rules", TYPE_STRING, {NULL}},
    {"ip6addrctl_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ip6addrctl_verbose", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ip6addrctl_policy", TYPE_STRING, {"ipv4_prefer", "ipv6_prefer", "AUTO", NULL}},
    {"keyboard", TYPE_STRING, {NULL}},
    {"keymap", TYPE_STRING, {"NO", NULL}},
    {"keyrate", TYPE_STRING, {"slow", "normal", "fast", "NO", NULL}},
    {"keybell", TYPE_STRING, {"off", "NO", NULL}},
    {"keychange", TYPE_STRING, {"NO", NULL}},
    {"cursor", TYPE_STRING, {"normal", "blink", "destructive", "NO", NULL}},
    {"scrnmap", TYPE_STRING, {"NO", NULL}},
    {"font8x16", TYPE_STRING, {"NO", NULL}},
    {"font8x14", TYPE_STRING, {"NO", NULL}},
    {"font8x8", TYPE_STRING, {"NO", NULL}},
    {"blanktime", TYPE_INT, {NULL}},
    {"saver", TYPE_STRING, {"NO", NULL}},
    {"moused_nondefault_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"moused_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"moused_type", TYPE_STRING, {"auto", NULL}},
    {"moused_port", TYPE_STRING, {NULL}},
    {"moused_flags", TYPE_STRING, {NULL}},
    {"mousechar_start", TYPE_STRING, {"NO", NULL}},
    {"allscreens_flags", TYPE_STRING, {NULL}},
    {"allscreens_kbdflags", TYPE_STRING, {NULL}},
    {"mta_start_script", TYPE_STRING, {NULL}},
    {"sendmail_enable", TYPE_BOOL, {"YES", "NO", "NONE", NULL}},
    {"sendmail_pidfile", TYPE_STRING, {NULL}},
    {"sendmail_procname", TYPE_STRING, {NULL}},
    {"sendmail_flags", TYPE_STRING, {NULL}},
    {"sendmail_cert_create", TYPE_BOOL, {"YES", "NO", NULL}},
    {"sendmail_submit_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"sendmail_submit_flags", TYPE_STRING, {NULL}},
    {"sendmail_outbound_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"sendmail_outbound_flags", TYPE_STRING, {NULL}},
    {"sendmail_msp_queue_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"sendmail_msp_queue_flags", TYPE_STRING, {NULL}},
    {"sendmail_rebuild_aliases", TYPE_BOOL, {"YES", "NO", NULL}},
    {"auditd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"auditd_program", TYPE_STRING, {NULL}},
    {"auditd_flags", TYPE_STRING, {NULL}},
    {"auditdistd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"auditdistd_program", TYPE_STRING, {NULL}},
    {"auditdistd_flags", TYPE_STRING, {NULL}},
    {"cron_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"cron_program", TYPE_STRING, {NULL}},
    {"cron_dst", TYPE_BOOL, {"YES", "NO", NULL}},
    {"cron_flags", TYPE_STRING, {NULL}},
    {"cfumass_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"cfumass_dir", TYPE_STRING, {NULL}},
    {"cfumass_image", TYPE_STRING, {NULL}},
    {"lpd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"lpd_program", TYPE_STRING, {NULL}},
    {"lpd_flags", TYPE_STRING, {NULL}},
    {"nscd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"chkprintcap_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"chkprintcap_flags", TYPE_STRING, {NULL}},
    {"dumpdev", TYPE_STRING, {"AUTO", "NO", NULL}},
    {"dumpon_flags", TYPE_STRING, {NULL}},
    {"dumpdir", TYPE_STRING, {NULL}},
    {"savecore_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"savecore_flags", TYPE_STRING, {NULL}},
    {"service_delete_empty", TYPE_BOOL, {"YES", "NO", NULL}},
    {"crashinfo_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"crashinfo_program", TYPE_STRING, {NULL}},
    {"quota_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"check_quotas", TYPE_BOOL, {"YES", "NO", NULL}},
    {"quotaon_flags", TYPE_STRING, {NULL}},
    {"quotaoff_flags", TYPE_STRING, {NULL}},
    {"quotacheck_flags", TYPE_STRING, {NULL}},
    {"accounting_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"firstboot_sentinel", TYPE_STRING, {NULL}},
    {"sysvipc_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"linux_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"linux_mounts_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"clear_tmp_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"clear_tmp_X", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ldconfig_insecure", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ldconfig_paths", TYPE_STRING, {NULL}},
    {"ldconfig32_paths", TYPE_STRING, {NULL}},
    {"ldconfigsoft_paths", TYPE_STRING, {NULL}},
    {"ldconfig_local_dirs", TYPE_STRING, {NULL}},
    {"ldconfig_local32_dirs", TYPE_STRING, {NULL}},
    {"ldconfig_localsoft_dirs", TYPE_STRING, {NULL}},
    {"kern_securelevel_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"kern_securelevel", TYPE_STRING, {NULL}},
    {"update_motd", TYPE_BOOL, {"YES", "NO", NULL}},
    {"entropy_boot_file", TYPE_STRING, {NULL}},
    {"entropy_file", TYPE_STRING, {NULL}},
    {"entropy_dir", TYPE_STRING, {NULL}},
    {"entropy_save_sz", TYPE_STRING, {NULL}},
    {"entropy_save_num", TYPE_STRING, {NULL}},
    {"harvest_mask", TYPE_STRING, {NULL}},
    {"osrelease_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"osrelease_file", TYPE_STRING, {NULL}},
    {"osrelease_perms", TYPE_STRING, {NULL}},
    {"dmesg_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"watchdogd_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"watchdogd_flags", TYPE_STRING, {NULL}},
    {"watchdogd_timeout", TYPE_STRING, {NULL}},
    {"watchdogd_shutdown_timeout", TYPE_STRING, {NULL}},
    {"devfs_rulesets", TYPE_STRING, {NULL}},
    {"devfs_system_ruleset", TYPE_STRING, {NULL}},
    {"devfs_set_rulesets", TYPE_STRING, {NULL}},
    {"devfs_load_rulesets", TYPE_BOOL, {"YES", "NO", NULL}},
    {"performance_cx_lowest", TYPE_STRING, {NULL}},
    {"performance_cpu_freq", TYPE_STRING, {NULL}},
    {"economy_cx_lowest", TYPE_STRING, {NULL}},
    {"economy_cpu_freq", TYPE_STRING, {NULL}},
    {"virecover_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"ugidfw_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"bsdextended_script", TYPE_STRING, {NULL}},
    {"newsyslog_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"newsyslog_flags", TYPE_STRING, {NULL}},
    {"mixer_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"opensm_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rctl_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"rctl_rules", TYPE_STRING, {NULL}},
    {"iovctl_files", TYPE_STRING, {NULL}},
    {"jail_enable", TYPE_BOOL, {"YES", "NO", NULL}},
    {"jail_conf", TYPE_STRING, {NULL}},
    {"jail_confwarn", TYPE_BOOL, {"YES", "NO", NULL}},
    {"jail_parallel_start", TYPE_BOOL, {"YES", "NO", NULL}},
    {"jail_list", TYPE_STRING, {NULL}},
    {"jail_reverse_stop", TYPE_BOOL, {"YES", "NO", NULL}}
};

#endif
