name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Triggers workflow when tags starting with 'v' are created
  pull_request:
    branches: [ "main" ]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Run tests
        run: make test
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: checkrc
